embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery-ui.min.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.easytabs.js
    - public/javascripts/core.js
    - public/javascripts/diQuery-collapsiblePanel.js
    - public/javascripts/application.js

stylesheets:
  main:
    - public/stylesheets/reset.css
    - public/stylesheets/grids.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/awesome-buttons.css
    - public/stylesheets/flutie_mod.css
    - public/stylesheets/diQuery-collapsiblePanel.css
    - public/stylesheets/main.css