site:
  base_url: "http://localhost:3000"
  name: "Wf4Ever ROBox"
  main_logo_image: "wf4ever-logo.png"
 
default_page_size: 20
max_page_size: 50

dropbox:
  consumer_key: "{{Get this from Dropbox}}"
  consumer_secret: "{{Get this from Dropbox}}"
  
rosrs:
  base_uri: "{{..}}"
  admin_username: "{{..}}"
  admin_password: "{{..}}"

ums:
  uri: "http://sandbox.wf4ever-project.org/users/"

sync:
  pending_jobs_resubmit_after: 15  # In minutes
