site:
  base_url: "http://localhost:3000"
  name: "Wf4Ever Dropbox RO Connector"
  main_logo_image: "wf4ever-logo.png"
 
default_page_size: 20
max_page_size: 50

dropbox:
  consumer_key: "{{..}}"
  consumer_secret: "{{..}}"