require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DropboxAccountsController do

  def mock_dropbox_account(stubs={})
    @mock_dropbox_account ||= mock_model(DropboxAccount, stubs).as_null_object
  end

end
